# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/node:12.10.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache deÂ¯pendencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Setup npmrc with the npm token
          command: |
            rm -f .npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: Install NPM packages
          command: yarn

      # Save cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: yarn test --ci --bail --runInBand --coverage

      - run:
          name: Build application
          command: NODE_ENV=production yarn build

      # Copy lib to artifacts
      - store_artifacts:
          path: ~/repo/lib
          destination: /lib

      # Copy coverage to artifacts
      - store_artifacts:
          path: ~/repo/coverage
          destination: /coverage

      # Copy code report to artifacts
      - store_artifacts:
          path: ~/repo/code-report
          destination: /code-report
